version: '3'

services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: softy-pinko-back-end:task4 
    ports:
      - 5252:525
  # Add any additional configuration for your back-end service here
  
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: softy-pinko-front-end:task4
    ports:
      - 9000:9000
    depends_on:                
      - back-end
   # Add any additional configuration for your frontend service here
