# Base image
FROM ubuntu:latest

# Update APT
RUN apt-get update

# Upgrade currently installed software
RUN apt-get upgrade -y

# Set the command to be run when the container starts
CMD ["echo", "Hello, World!"]
