version: '3'

services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: softy-pinko-back-end:task4 
  # Add any additional configuration for your back-end service here
  
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: softy-pinko-front-end:task4
    depends_on:                
      - back-end
   # Add any additional configuration for your frontend service here
  
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: softy-pinko-proxy:task5
    ports:
      - 80:80
    depends_on:
      - back-end
      - front-end
   # Add any additional configuration for your proxy service here
